stages:
  split:
    cmd: python split.py --data_path /Users/pauldev/delo/projects/risk-ai-workshop/notebooks/data/default.csv
    deps:
    - ../../notebooks/data/default.csv
    - split.py
    params:
    - split.file_read_params
    - split.non_target_cols
    - split.seed
    - split.target_col
    - split.test_ratio
    - split.train_ratio
    outs:
    - ../../notebooks/data/split
  fit_train:
    cmd: python fit.py --stage_name fit_train
    deps:
    - ../../notebooks/data/split
    - fit.py
    params:
    - fit_train.data_in_folder
    - fit_train.feature_filenames
    - fit_train.file_read_params
    - fit_train.model_params
    - fit_train.seed
    - fit_train.target_filenames
    outs:
    - ../../notebooks/data/fit_train
  evaluate_fit_train:
    cmd: python evaluate.py --stage_name evaluate_fit_train
    deps:
    - ../../notebooks/data/fit_train
    - ../../notebooks/data/split
    - evaluate.py
    params:
    - data_models
    - evaluate_fit_train.data_in_folder
    - evaluate_fit_train.feature_filename
    - evaluate_fit_train.file_read_params
    - evaluate_fit_train.model_in_folder
    - evaluate_fit_train.target_filename
  fit_selected_model:
    cmd: python fit.py --stage_name fit_selected_model
    deps:
    - ../../notebooks/data/split
    - fit.py
    params:
    - fit_selected_model.data_in_folder
    - fit_selected_model.feature_filenames
    - fit_selected_model.file_read_params
    - fit_selected_model.model_params
    - fit_selected_model.seed
    - fit_selected_model.target_filenames
    outs:
    - ../../notebooks/data/fit_selected_model
  evaluate_fit_test:
    cmd: python evaluate.py --stage_name evaluate_fit_test
    deps:
    - ../../notebooks/data/fit_selected_model
    - ../../notebooks/data/split
    - evaluate.py
    params:
    - data_models
    - evaluate_fit_test.data_in_folder
    - evaluate_fit_test.feature_filename
    - evaluate_fit_test.file_read_params
    - evaluate_fit_test.model_in_folder
    - evaluate_fit_test.target_filename
