split:
  seed: 42
  train_ratio: 0.40
  test_ratio: 0.20
  target_col: "default"
  non_target_cols: ["gender", "occupation", "activity"]
  file_read_params:
    delimiter: ","

fit_train:
  seed: 42
  data_in_folder: "split"
  feature_filenames: ["X-train.csv"]
  target_filenames: ["y-train.csv"]
  file_read_params:
    delimiter: ","
  model_params:
    logistic_regression:
      name: "LogisticRegression"
      hyperparams: {"C": 1, "random_state": 42}
    decision_tree_classifier:
      name: "DecisionTreeClassifier"
      hyperparams: {"criterion": gini, "random_state": 42}
    random_forest_classifier:
      name: "RandomForestClassifier"
      hyperparams: {'n_estimators': 10, "random_state": 42}

evaluate_fit_train:
  data_in_folder: "split"
  model_in_folder: "fit_train"
  feature_filename: "X-validate.csv"
  target_filename: "y-validate.csv"
  file_read_params:
    delimiter: ","

data_models:
  domain_values:
    gender: [0, 1]
    occupation: [0, 1]
    activity: [0, 1]
    default: [0, 1]

fit_selected_model:
  seed: 42
  data_in_folder: "split"
  feature_filenames: ["X-train.csv", "X-validate.csv"]
  target_filenames: ["y-train.csv", "y-validate.csv"]
  file_read_params:
    delimiter: ","
  model_params:
    decision_tree_classifier:
      name: "DecisionTreeClassifier"
      hyperparams: {"criterion": gini, "random_state": 42}

evaluate_fit_test:
  data_in_folder: "split"
  model_in_folder: "fit_selected_model"
  feature_filename: "X-test.csv"
  target_filename: "y-test.csv"
  file_read_params:
    delimiter: ","

